---
title: "Brouillon rendu"
format: 
  html:
    citeproc: false
    filters:
      - "citeproc.lua"
      - "wordcount.lua"
editor: visual
author: "jacopo hilde leopold"
code-fold: true
---

```{r, echo = FALSE, message = FALSE}
rm(list=ls(all=TRUE))
library(ggplot2)
library(vroom)
library(dplyr)
library(tidyr)
library(knitr)
library(here)
library(plotly)
library(here)
library(tidyverse)

here::i_am("M2SES.Rproj")

#importer les données

Annuaire <- vroom("fr-en-annuaire-education.csv")
ParcourSup <- vroom("fr-esr-parcoursup.csv")
Eloignement <- vroom("fr-en-indice_eloignement_lycee_ap2020.csv")

IPS_2016_2022 <- vroom("fr-en-ips_lycees.csv")
IPS_2022_2023 <- vroom("fr-en-ips-lycees-ap2022.csv")
IPS_2023_2024 <- vroom("fr-en-ips-lycees-ap2023.csv")


#filtrer les années pour IVAL

IVAL_gt <- vroom("fr-en-indicateurs-de-resultat-des-lycees-gt_v2.csv")


IVAL_gt <-IVAL_gt %>% filter(Année == 2016 | Année==2020 | Année==2024)

#faire pivoter les IVAL pour les avoirs en colomne et se débarraser des lignes par années.

IVAL_gt <- IVAL_gt %>% rename(IVAL = `Valeur ajoutée du taux de réussite - Toutes séries`) 

IVAL_gt %>%
  count(UAI) %>%
  filter(n > 1)

IVAL_gt <- IVAL_gt %>% select(UAI, Année, IVAL, Secteur, Académie,`Valeur ajoutée du taux d'acces 2nde-bac`, `Taux d'accès 2nde-bac`) %>%
  mutate(secteur_public = if_else(Secteur == "public", 1, 0)) %>% select(-Secteur) |>
  pivot_wider(id_cols = c(UAI, Académie),
        names_from = Année,
        values_from = c(IVAL, `Taux d'accès 2nde-bac`,`Valeur ajoutée du taux d'acces 2nde-bac` ),
        names_glue = "{.value}_{Année}")

IVAL_gt %>%
  count(UAI) %>%
  filter(n > 1)


#Pareil pour l'éloignement

Eloignement <- Eloignement %>% filter(Année=="2020" | Année=="2024" ) %>%  select(UAI, Année, Académie, `Indice éloignement` ) %>%
    pivot_wider(id_cols = c(UAI, Académie),
        names_from = Année,
        values_from = `Indice éloignement`,
        names_glue = "{.value}_{Année}")


Eloignement %>%
  count(UAI) %>%
  filter(n > 1)


#il y avait encore des doublons, mtn c'est bon l'équipe!


# Pivoter et unifier les tables IPS

IPS_pivot_2016 <- IPS_2016_2022 |> select(`Rentrée scolaire`, Académie, UAI, `IPS voie GT`, Secteur) |>
  pivot_wider(id_cols = c(UAI,Académie), names_from = 'Rentrée scolaire',
              values_from = 'IPS voie GT', , names_prefix = "IPS ")

IPS_pivot_2022 <- IPS_2022_2023 |> select(`Rentrée scolaire`, UAI,  `IPS voie GT`) |>
  pivot_wider(id_cols = UAI, names_from = 'Rentrée scolaire',
              values_from = 'IPS voie GT', , names_prefix = "IPS ")

IPS_pivot_2024 <- IPS_2023_2024 |> select(`Rentrée scolaire`, UAI, `IPS voie GT`) |>
  pivot_wider(id_cols = UAI, names_from = 'Rentrée scolaire',
              values_from = 'IPS voie GT', , names_prefix = "IPS ")

IPS_gt <- IPS_pivot_2016 |> left_join(IPS_pivot_2022) |> left_join(IPS_pivot_2024) |> filter(!is.na(`IPS 2016-2017`)) %>% select(`IPS 2016-2017`, `IPS 2020-2021`,`IPS 2024-2025`, UAI, Académie )


IPS_gt %>%
  count(UAI) %>%
  filter(n > 1)


IVAL_IPS_gt <- inner_join(IVAL_gt,IPS_gt, by = c("UAI", "Académie"))

IVAL_IPS_gt %>%
  count(UAI) %>%
  filter(n > 1)

IVAL_IPS_gt <- IVAL_IPS_gt %>% inner_join(Eloignement, by = c("UAI", "Académie"))

##normalement ce code permet d'avoir sur 1 seul (beau :) ) tableau : lycée, uai en 1 seule lignes, avec tous les indicateurs qui nous intéressent en 2016 - 2020 - 2024 (sauf l'éloigement qu'on a pas en 2016). Mtn on peut s'amuser avec le tableau pour faire des graphs et des regressions !!! (j'ai gardé les infos région, département, Académie pour peut être regarder des effets par zones géogarphique).
# Bon enft non j'ai du suppr les académies, dept , region donc les graphs ci dessous marchent plus, je vais voir comment faire.

# En théorie j'ai reussi a fixer le problème avec academie

```



```{r}

# Indice moyen d'éloignement par académie ?

Eloi2024_Acad <- IVAL_IPS_gt %>% group_by(Académie)  %>% summarise(moyenne_eloignement_2024 = mean(`Indice éloignement_2024`, na.rm = TRUE)) 
  
ggplot(Eloi2024_Acad, aes(x = fct_reorder(Académie, moyenne_eloignement_2024), 
           y = moyenne_eloignement_2024, 
           fill = moyenne_eloignement_2024)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(
    title = "Indice moyen d'éloignement par académie (2024)",
    x = "Académie",
    y = "Indice moyen"
  ) + theme(axis.text.x = element_text(angle = 45, hjust = 1))

```



```{r}

# nombre de lycées privés par académie.

priv_acad <- IVAL_IPS_gt %>%
  filter(secteur_public == 0) %>%         
  group_by(Académie) %>%
  summarise(nb_prives = n()) 

ggplot(priv_acad, aes(x=Académie, y=nb_prives, fill=nb_prives)) + geom_bar(stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
#IPS moyen par Académie. Peut être qu'il faut recflechir à des pondérations...
IVAL_IPS_gt <- IVAL_IPS_gt %>%
  mutate(IPS_moy_lycee = rowMeans(
    select(., `IPS 2016-2017`, `IPS 2020-2021`, `IPS 2024-2025`),
    na.rm = TRUE
  ))

IPS_acad <- IVAL_IPS_gt %>%
  group_by(Académie) %>%
  summarise(IPS_moyen = mean(IPS_moy_lycee, na.rm = TRUE))

IPS_acad %>% ggplot(aes(x=Académie, y=IPS_moyen, fill=IPS_moyen)) + geom_bar(stat="identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1))

```
